# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lidar_data.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='lidar_data.proto',
  package='enac',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x10lidar_data.proto\x12\x04\x65nac\":\n\x05Lidar\x12\x0e\n\x06nb_pts\x18\x01 \x01(\x05\x12\x0e\n\x06\x61ngles\x18\x02 \x03(\x02\x12\x11\n\tdistances\x18\x03 \x03(\x02\x62\x06proto3'
)




_LIDAR = _descriptor.Descriptor(
  name='Lidar',
  full_name='enac.Lidar',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nb_pts', full_name='enac.Lidar.nb_pts', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='angles', full_name='enac.Lidar.angles', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='distances', full_name='enac.Lidar.distances', index=2,
      number=3, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=84,
)

DESCRIPTOR.message_types_by_name['Lidar'] = _LIDAR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Lidar = _reflection.GeneratedProtocolMessageType('Lidar', (_message.Message,), {
  'DESCRIPTOR' : _LIDAR,
  '__module__' : 'lidar_data_pb2'
  # @@protoc_insertion_point(class_scope:enac.Lidar)
  })
_sym_db.RegisterMessage(Lidar)


# @@protoc_insertion_point(module_scope)
