# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: robot_state.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='robot_state.proto',
  package='enac',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x11robot_state.proto\x12\x04\x65nac\"&\n\x06Travel\x12\r\n\x05theta\x18\x01 \x01(\x02\x12\r\n\x05speed\x18\x02 \x01(\x02\x62\x06proto3'
)




_TRAVEL = _descriptor.Descriptor(
  name='Travel',
  full_name='enac.Travel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='theta', full_name='enac.Travel.theta', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='speed', full_name='enac.Travel.speed', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=65,
)

DESCRIPTOR.message_types_by_name['Travel'] = _TRAVEL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Travel = _reflection.GeneratedProtocolMessageType('Travel', (_message.Message,), {
  'DESCRIPTOR' : _TRAVEL,
  '__module__' : 'robot_state_pb2'
  # @@protoc_insertion_point(class_scope:enac.Travel)
  })
_sym_db.RegisterMessage(Travel)


# @@protoc_insertion_point(module_scope)
