# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: robot_state.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11robot_state.proto\x12\x04\x65nac\"/\n\x08Position\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\r\n\x05theta\x18\x03 \x01(\x02\"/\n\x05Speed\x12\n\n\x02vx\x18\x01 \x01(\x02\x12\n\n\x02vy\x18\x02 \x01(\x02\x12\x0e\n\x06vtheta\x18\x03 \x01(\x02\"W\n\x04Odom\x12 \n\x08position\x18\x01 \x01(\x0b\x32\x0e.enac.Position\x12\x1a\n\x05speed\x18\x02 \x01(\x0b\x32\x0b.enac.Speed\x12\x11\n\ttimestamp\x18\x03 \x01(\x01\".\n\x0eHolonomicSpeed\x12\r\n\x05speed\x18\x01 \x01(\x02\x12\r\n\x05\x61ngle\x18\x02 \x01(\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'robot_state_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _POSITION._serialized_start=27
  _POSITION._serialized_end=74
  _SPEED._serialized_start=76
  _SPEED._serialized_end=123
  _ODOM._serialized_start=125
  _ODOM._serialized_end=212
  _HOLONOMICSPEED._serialized_start=214
  _HOLONOMICSPEED._serialized_end=260
# @@protoc_insertion_point(module_scope)
